import type { Experience } from "@/types/experience"

export const EXPERIENCES = [
  {
    id: "livefx 2026",
    title: "LiveFx 2026",
    company: "SIW実行委員会",
    period: "2026",
    post: "プロジェクトマネージャー、フロントエンドエンジニア",
    category: "開発プロジェクト",
    status: "完了",
    description:
      "慈恵学園の専門学校のグループの入学式イベントで、演者側の MIDI コントローラーによる画面演出の操作を、リアルタイムに観客のスマートフォンへ視覚効果として同期表示させました。クライアントから桜を咲かせるインタラクティブな演出を追加しました。",
    skills: [
      "React",
      "Vite",
      "TypeScript",
      "WebSocket",
      "k8s",
      "Express",
      "AWS ECS",
      "Prometheus",
      "Grafana",
    ],
    url: "https://zenn.dev/siw/articles/5e3ba45a682a91",
  },
  {
    id: "imaaiteru-kun",
    title: "今空いてる？君",
    company: "Team Idea",
    period: "2026",
    post: "プロダクトマネージャー",
    category: "開発プロジェクト",
    status: "完了",
    description:
      "ユーザが出発地と日付を入力すると、近隣のイベント情報を取得し、時刻表などと組み合わせて駅の混雑を予測するWebアプリケーション",
    skills: ["Next.js", "TypeScript", "React", "Tailwind CSS", "Gemini SDK"],
    url: "https://github.com/opendata-idea/imaaiteru-kun",
  },
  {
    id: "worktrack",
    title: "WorkTrack",
    company: "SIW Ideaチーム",
    period: "2025",
    post: "プロダクトマネージャー、テスターエンジニア",
    category: "開発プロジェクト",
    status: "完了",
    description:
      "企業連携の授業で、BSC（ブレインスタッフコンサルティング株式会社）様の社員方が、顧客（学校・企業）のサポートにかかった工数を集計するシステムを開発しています。",
    skills: ["PHP", "Apache", "MySQL", "AWS"],
    url: "https://zenn.dev/tkszenn/articles/1d5e63cfd0d5bc",
  },
  {
    id: "livefx 2025",
    title: "LiveFx 2025",
    company: "SIW実行委員会",
    period: "2025",
    post: "プロジェクトマネージャー、フロントエンドエンジニア",
    category: "開発プロジェクト",
    status: "完了",
    description:
      "慈恵学園の専門学校のグループの入学式イベントで、演者側の MIDI コントローラーによる画面演出の操作を、リアルタイムに観客のスマートフォンへ視覚効果として同期表示させました。",
    skills: [
      "React",
      "TypeScript",
      "WebSocket",
      "k8s",
      "Express",
      "AWS",
      "Prometheus",
      "Grafana",
    ],
    url: "https://zenn.dev/tkszenn/articles/2e73439f678488",
  },
  {
    id: "autonomous-driving",
    title: "自動運転AIチャレンジ2024 予選出場",
    company: "自動車技術会",
    period: "2024",
    post: "プロジェクトマネージャー",
    category: "競技",
    status: "参加",
    description:
      "オンラインのシミュレーションで実施します。予選の競技はデジタルツイン指向のAWSIMを用いてコースをより速く走行することを目指します",
    skills: ["ROS", "Ubuntu", "Docker"],
  },
  {
    id: "drocats",
    title: "第一回ドロカツ プログラミング部門優勝",
    company: "ドロカツ実行委員会",
    period: "2024",
    post: "プロジェクトマネージャー",
    category: "競技",
    status: "優勝",
    description: "ドローンのプログラミングや操縦に関する全国大会です。",
    skills: ["Python"],
    url: "https://www.drokatsu.com/news/drokatsutaikai-zenkoku",
  },
] satisfies Experience[]
