import type { Project } from "@/types/project"

export const PROJECTS = [
  {
    title: "Clipgest",
    description:
      "気になった Web ページの URL をブラウザ拡張から一瞬で保存して、ダッシュボードで週次・月次ダイジェストにまとめる Web アプリ",
    image:
      "https://github.com/lvncer/quicklinks/blob/main/public/images/toppage.jpeg?raw=true",
    technologies: [
      "Next.js",
      "Go",
      "Gin",
      "Ent",
      "Google Chrome Extension",
      "Supabase",
      "Clerk",
      "Docker",
    ],
    category: "Webアプリケーション",
    status: "公開中",
    year: "2025",
    github: "https://github.com/lvncer/clipgest",
    live: "https://www.clipgest.com/about",
  },
  {
    title: "Coeur",
    description: "glb モデルを AI が自然言語で制御できる MCP リモートサーバー",
    video: "/coeur-mcp.mp4",
    technologies: [
      "Nodejs",
      "Express",
      "React",
      "VRM",
      "stdio / SSE",
      "MCP",
      "Upstash Redis",
      "Railway",
    ],
    category: "ツール",
    status: "開発中",
    year: "2025",
    github: "https://github.com/lvncer/coeur",
  },
  {
    title: "Kaiwa Dash",
    description: "AI との会話練習でコミュニケーション力を向上させる Web アプリ",
    image:
      "https://github.com/lvncer/kaiwa-dash/raw/main/public/images/result.png",
    technologies: [
      "Next.js",
      "TypeScript",
      "OpenAPI",
      "Tailwind CSS",
      "Shadcn UI",
      "Vercel",
    ],
    category: "Webアプリケーション",
    status: "停止",
    year: "2025",
    github: "https://github.com/lvncer/kaiwa-dash",
  },
  {
    title: "cc-changelogs",
    description:
      "Claude Code リポジトリの CHANGELOG.md 変更を 5 分毎に監視し、DeepL で日本語翻訳して Discord に美しい通知を送るシステムです。",
    image: "/cc-changelog.png",
    technologies: [
      "Node.js",
      "Discord.js",
      "DeepL API",
      "GitHub API",
      "TypeScript",
    ],
    category: "ツール",
    status: "停止",
    year: "2025",
    github: "https://github.com/lvncer/cc-changelogs",
  },
  {
    title: "cclog",
    description:
      "Claude Code の会話履歴をコマンドライン上で効率的に閲覧・管理するためのツール。過去のセッションを簡単に検索、閲覧、再開できます。",
    image:
      "https://raw.githubusercontent.com/lvncer/cclog/HEAD/public/images/sessions-preview.jpeg",
    technologies: ["TypeScript"],
    category: "ツール",
    status: "停止",
    year: "2025",
    github: "https://github.com/lvncer/echoes",
  },
  {
    title: "Echoes",
    description:
      "AIの3Dモデルと直接会話ができるWebアプリ。音声入力から認識・合成・出力までできます。",
    image: "/echoes.jpeg",
    technologies: [
      "Next.Js",
      "TypeScript",
      "React Three Fiber",
      "Zustand",
      "Gemini",
    ],
    category: "Webアプリケーション",
    status: "停止",
    year: "2025",
    github: "https://github.com/lvncer/echoes",
  },
  {
    title: "NameCard",
    description:
      "Markdown ファイルから美しい名刺を作成・エクスポートできる CLI ツール",
    image: "/name-card.jpg",
    technologies: [
      "Next.Js",
      "TypeScript",
      "NPM",
      "Commander",
      "Tailwind CSS",
      "Puppeteer",
    ],
    category: "ライブラリ",
    status: "停止",
    year: "2025",
    github: "https://github.com/lvncer/name-card",
  },
  {
    title: "LightningTalks",
    description:
      "ライトニングトーク管理サイト。学校でLTを行いたいという意見が多かったため作成しました。学校の学生だけでなく、外部のユーザも登録可能です。",
    image: "/lt.png",
    technologies: ["Next.Js", "TypeScript", "Neon", "Clerk"],
    category: "Webアプリケーション",
    status: "公開中",
    year: "2025",
    github: "https://github.com/lvncer/lt",
    live: "https://siw-lt.vercel.app",
  },
  {
    title: "Bookmarks",
    description:
      "シンプルなブックマークマネージャー。カテゴリ別にブックマークを管理できます。",
    image: "/bookmark.png",
    technologies: ["Next.Js", "TypeScript", "Supabase", "Clerk"],
    category: "Webアプリケーション",
    status: "停止",
    year: "2025",
    github: "https://github.com/lvncer/bookmarks",
  },
  {
    title: "Next SNS",
    description:
      "シンプルなSNSのクローンサイト。フルスタックで作成した初めてのWebアプリです。",
    image: "/nextsns.png",
    technologies: [
      "Next.js",
      "TypeScript",
      "Node.Js",
      "Express",
      "Redux",
      "Tailwind CSS",
      "MongoDB",
    ],
    category: "Webアプリケーション",
    status: "停止",
    year: "2024",
    github: "https://github.com/lvncer/nextsns",
  },
] satisfies Project[]
